---
# Required variables
user_dir: mattc

# Homebrew variables
homebrew_packages:
  - wget
  - unrar

# Node variables
node_packages:
  - grunt-cli
  - bower
yeoman_generators:
  - webapp
  - bootstrap
  - backbone
  - marionette
  - ember

# Non package-manager applications
apps_to_install:
  - name: Adium
    appname: Adium
    location: http://downloads.sourceforge.net/project/adium/Adium_1.5.10.dmg?r=&ts=1407070248&use_mirror=cznic
    replace: no
  - name: Alfred
    appname: Alfred 2.app
    location: http://cachefly.alfredapp.com/Alfred_2.3_264.zip
    replace: no
  - name: PHPStorm
    appname: PhpStorm
    location: http://download.jetbrains.com/webide/PhpStorm-7.1.3.dmg
    replace: no
  - name: PyCharm Professional Edition
    appname: PyCharm
    location: http://download.jetbrains.com/python/pycharm-professional-3.4.1.dmg
    replace: no
  - name: Sequel Pro
    appname: Sequel Pro
    location: https://sequel-pro.googlecode.com/files/sequel-pro-1.0.2.dmg
    replace: no
  - name: SourceTree
    appname: SourceTree
    location: http://downloads.atlassian.com/software/sourcetree/SourceTree_1.9.7.dmg
    replace: no
  - name: Sublime Text
    appname: Sublime Text
    location: http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203059.dmg
    replace: no