# Set up PHP using Homebrew
  -	name: Tap josegonzalez/PHP
    command:  brew tap josegonzalez/php
    ignore_errors: yes

  - name: Tap homebrew/dupes
    command:  brew tap josegonzalez/php
    ignore_errors: yes

  - name: Update Homebrew
    homebrew: update_homebrew=yes

  - name: Install PHP
    homebrew: >
      name=php54
      install_options=with-fpm,with-imap,without-apache,with-debug
      state=latest