---

  - name: Install PHP
    homebrew:
      name: "php{{ php_brew_version }}"
      state: latest
    tags:
      - php

  - name: Install PHP modules
    homebrew:
      name: "php{{php_brew_version}}-{{ item }}"
      state: latest
    with_items: "{{ php_modules }}"
    tags:
      - php

  - name: Ensure correct PHP version is symlinked in Apache config
    lineinfile:
      dest: "{{ apache_config_file }}"
      line: "LoadModule php5_module    /usr/local/opt/php{{ php_brew_version }}/libexec/apache2/libphp5.so"
      regexp: "#LoadModule php5_module.+"
      state: present
    notify:
      - Restart Apache
    tags:
      - php

  - name: Ensure log directory exists and is writable
    file:
      path: "{{ php_error_log_path }}"
      state: directory
      group: "staff"
      mode: 0664
    sudo: yes
    tags:
      - php

  - name: Configure PHP
    template:
      src: php.ini.j2
      dest: "/usr/local/etc/php/{{ php_version }}/php.ini"
    tags:
      - php

  - name: Configure PHP-Opcache
    template:
      src: ext-opcache.ini.j2
      dest: "/usr/local/etc/php/{{ php_version }}/conf.d/ext-opcache.ini"
    when: "'opcache' in php_modules"
    tags:
      - php

  - name: Configure PHP Xdebug
    template:
      src: ext-xdebug.ini.j2
      dest: "/usr/local/etc/php/{{ php_version }}/conf.d/ext-xdebug.ini"
    when: "'xdebug' in php_modules"
  - include: composer.yml
